name: Buildtest Server Ubuntu/Jammy (amd64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Installing dependencies
      run: |
        sudo apt-get install -y --no-install-recommends build-essential curl ca-certificates sudo git lintian fakeroot pkg-config libudev-dev libssl-dev libapt-pkg-dev libclang-dev libpam0g-dev
    - name: Installing rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -sSf | sh -s -- -y
    - uses: actions/checkout@v3
    - name: Build packages
      run: |
        source ${HOME}/.cargo/env
        # eslint don't search in /usr/share/nodejs on github action ubuntu
        sudo mkdir -p /usr/share/nodejs
        sudo ln -s /usr/share/nodejs /usr/share/nodejs/node_modules
        if [ "${RUNNER_DEBUG}" = "1" ]; then
          ./build.sh debug
        else
          ./build.sh
        fi
    - name: Test packages
      run: |
        sudo apt install -y \
                ./packages/libjs-extjs_*_all.deb \
                ./packages/libjs-qrcodejs_*_all.deb \
                ./packages/libproxmox-acme-plugins_*_all.deb \
                ./packages/pbs-i18n_*_all.deb \
                ./packages/proxmox-backup-docs_*_all.deb \
                ./packages/proxmox-backup-server_*.deb \
                ./packages/proxmox-mini-journalreader_*.deb \
                ./packages/proxmox-widget-toolkit_*_all.deb \
                ./packages/pve-xtermjs_*.deb
        sudo apt install -y \
                ./packages/proxmox-backup-client_*.deb
        sudo apt install -y \
                ./packages/proxmox-backup-file-restore_*.deb
